
import "./globals.css";
import type { Metadata } from "next";
import MyModal from "@/components/MyModal";

export const metadata: Metadata = {
  title: "Trello 2.0 Clone",
  description: "Generated by SRayen",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <MyModal/>
      </body>
    </html>
  );
}